# Generated by Django 3.1.4 on 2020-12-15 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(auto_created=True, default=uuid.uuid4, max_length=80, unique=True)),
                ('access', models.CharField(max_length=50)),
            ],
        ),
    ]
